// Todo: styled-components theme 機能の活用

const BASE_CONTENT_BACK = '#ffffff';
const COLOR_PRIMARY = '#1876f2';
const BASE_TEXT_COLOR_PC = '#242424';
const BASE_TEXT_COLOR_SP = '#111111';

const COLOR = {
    BASE_TEXT_PC: BASE_TEXT_COLOR_PC,
    BASE_TEXT_SP: BASE_TEXT_COLOR_SP,

    BUTTON_PRIMARY_BACK: COLOR_PRIMARY,
    BUTTON_PRIMARY_TEXT: '#ffffff',
    BUTTON_SECONDARY_BACK: '#e6f2ff',
    BUTTON_SECONDARY_TEXT: '#2c84f5',

    CONTENT_BACK: '#ffffff',

    HEADER_BACK: '#3b5998',
    HEADER_SEARCH: 'rgba(255, 255, 255, .7)',

    HERO_CONTENTS_BACK: BASE_CONTENT_BACK,
    HERO_MESSAGE: '#65676b',

    MENU_ACTIVE: COLOR_PRIMARY,
    MENU_INACTIVE: '#65676b',

    NAVIGATION_BACK: BASE_CONTENT_BACK,

    POST_PREVIEW_BACK: BASE_CONTENT_BACK,
    POST_PREVIEW_HEADER_DATE_TEXT: '#787878',
    POST_PREVIEW_HEADER_DATE_ICON: '#9a9a9a',

    POST_PREVIEW_CARRIER_EVENT_BUSINESS_ICON: '#ffffff',
    POST_PREVIEW_CARRIER_EVENT_BUSINESS_ICON_WRAPPER_BACK: '#1876f2',
    POST_PREVIEW_CARRIER_EVENT_META_ROW: '#65676b',

    OPEN_DETAIL_LABEL_TEXT: '#65676b',
    OPEN_DETAIL_LABEL_BORDER: '#65676b',

    PERSONAL_INFO_ICON: '#969da8',

    SEPARATE_BORDER: '#c6c8cc',

    TAG_TEXT: '#787878',

    THUMBNAIL_BORDER: '#FFFFFF',
};

const FONT = {
    XXXXLARGE: '1.6rem',
    XXXLARGE: '1.3rem',
    XXLARGE: '1.2rem',
    XLARGE_XXLARGE: '1rem',
    XLARGE: '.9rem',
    LARGE_XLARGE: '.85rem',
    LARGE: '.8rem',
    MEDIUM_LARGE: '.75rem',
    MEDIUM: '.7rem',
    BASE_MEDIUM: '.65rem',
    BASE: '.6rem',
    SMALL: '.55rem',
    XSMALL: '.5rem',
    TINY: '.4rem',
};

const FONT_WEIGHT = {
    NORMAL: 400,
    BOLD: 600,
};

const CONTENTS = {
    GAP_PC: '.8rem',
    GAP_SP: '.5rem',
    MAX_WIDTH: '52rem',
    BORDER_RADIUS: '.4rem',
    BOX_SHADOW: '0 1px 2px rgba(0, 0, 0, .2)',
};

export { COLOR, FONT, FONT_WEIGHT, CONTENTS };
